language: go

go:
    - 1.10.x

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs github.com/mattn/go-sqlite3 github.com/jmoiron/sqlx
    - go get -u -d -tags=js github.com/flimzy/go-sql.js

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - gopherjs test github.com/flimzy/anki
    - go test github.com/flimzy/anki
